export default function getData() {
    return {
        authorizationItems: [
            {
                accountId: "7fb4aea1-042a-4224-a4fa-ad5500c2cfd4",
                actualEndDate: null,
                assigneeId: 180140,
                assigneeName: "test, author1",
                assigneeNameWithoutAccent: "test, author",
                assignmentCountry: "China",
                assignmentId: 210131,
                assignmentStatus: "",
                assignmentTypeName: null,
                authorizedCountry: "Albania",
                category: "Host",
                comments: null,
                employeeId: "",
                id: 458789,
                isAuthorized: true,
                isAutoFilledAssignment: false,
                isManual: false,
                isMyPwCUser: true,
                lastUpdatedBy: null,
                lastUpdatedByClient: false,
                lastUpdatedOn: null,
                restricted: false,
                revokeType: "None",
                startDate: "2021-11-22",
            },
            {
                accountId: "7fb4aea1-042a-4224-a4fa-ad5500c2cfd4",
                actualEndDate: null,
                assigneeId: 180140,
                assigneeName: "test, author2",
                assigneeNameWithoutAccent: "test, author",
                assignmentCountry: "Christmas Island",
                assignmentId: 210132,
                assignmentStatus: "",
                assignmentTypeName: null,
                authorizedCountry: "Albania",
                category: "Host",
                comments: null,
                employeeId: "",
                id: 458790,
                isAuthorized: false,
                isAutoFilledAssignment: false,
                isManual: false,
                isMyPwCUser: true,
                lastUpdatedBy: null,
                lastUpdatedByClient: false,
                lastUpdatedOn: null,
                restricted: false,
                revokeType: "None",
                startDate: "2021-11-11",
            },
            {
                accountId: "7fb4aea1-042a-4224-a4fa-ad5500c2cfd4",
                actualEndDate: null,
                assigneeId: 180141,
                assigneeName: "test, author3",
                assigneeNameWithoutAccent: "test, author",
                assignmentCountry: null,
                assignmentId: null,
                assignmentStatus: "",
                assignmentTypeName: null,
                authorizedCountry: "Albania",
                category: "Home",
                comments: null,
                employeeId: "",
                id: 458791,
                isAuthorized: true,
                isAutoFilledAssignment: true,
                isManual: false,
                isMyPwCUser: true,
                lastUpdatedBy: null,
                lastUpdatedByClient: false,
                lastUpdatedOn: null,
                restricted: false,
                revokeType: "None",
                startDate: null,
            },
        ]
    };
}